spring.application.name=backend
server.port=8080

spring.datesource.diver-class-name=org.h2.Driver
spring.datesource.sudename=sa
spring.datesource.password=

spring.jpa.hidernate.ddl-auto=update
spring.jpa.show-sql=true        
